// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41OJ2fFIm_apGJezWXH1DpL3gXs4isSk',
    appId: '1:1022830934583:web:0499c17133eff852f11db2',
    messagingSenderId: '1022830934583',
    projectId: 'emhealth-ee99c',
    authDomain: 'emhealth-ee99c.firebaseapp.com',
    storageBucket: 'emhealth-ee99c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41OJ2fFIm_apGJezWXH1DpL3gXs4isSk',
    appId: '1:1022830934583:android:0499c17133eff852f11db2',
    messagingSenderId: '1022830934583',
    projectId: 'emhealth-ee99c',
    storageBucket: 'emhealth-ee99c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0r2NtzNYE7S14HmH4YG_io44GrEXJnL8',
    appId: '1:1022830934583:ios:482982b840d3e262f11db2',
    messagingSenderId: '1022830934583',
    projectId: 'emhealth-ee99c',
    storageBucket: 'emhealth-ee99c.firebasestorage.app',
    iosBundleId: 'com.app.emhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0r2NtzNYE7S14HmH4YG_io44GrEXJnL8',
    appId: '1:1022830934583:ios:482982b840d3e262f11db2',
    messagingSenderId: '1022830934583',
    projectId: 'emhealth-ee99c',
    storageBucket: 'emhealth-ee99c.firebasestorage.app',
    iosBundleId: 'com.app.emhealth',
  );
}

